#####################################################################################
# Project: MakeBind
# File: mb_modules.mk
# Description: Module structure for MakeBind
# Author: AntonioCS
# License: MIT License
#####################################################################################
### NOTE: This file is autogenerated, do not edit it directly as it will be overwritten
### NOTE 2: Use mb/modules/list, mb/modules/add/<module>[/<module>], mb/modules/remove/<module>[/<module>] to manage your modules
### NOTE 3: If a module depends on another module, that module will automatically be added
mb_project_modules_loaded := docker docker_compose project_builder localstack
