#####################################################################################
# Project: MakeBind
# File: modules/project-builder/project_builder.mk
# Description: Project Builder module for MakeBind
# Author: AntonioCS
# License: MIT License
#####################################################################################
ifndef __MB_MODULES_PROJECT_BUILDER__
__MB_MODULES_PROJECT_BUILDER__ := 1

ifndef __MB_MODULES_PROJECT_BUILDER_FUNCTIONS__
__MB_MODULES_PROJECT_BUILDER_FUNCTIONS__ := 1

mb_debug_pb ?= $(mb_debug)
mb_pb_folder ?= $(mb_modules_path)/project-builder
## NOTE: The contents seems to be inside a folder (generated by github)
## so the output folder is project_templates-main
mb_pb_tpl_url ?= https://github.com/AntonioCS/project_templates/archive/refs/heads/main.zip
mb_pb_tpl_download_to ?= $(mb_makebind_tmp_path)/project_templates.zip
mb_pb_tpl_unzip_to ?= $(mb_makebind_tmp_path)
mb_pb_tpl_folder ?= $(mb_makebind_tmp_path)/project_templates-main

mb_pb_project_builders ?= php_symfony php_laravel


define mb_pb_fetch_project_templates
$(if $(wildcard $(mb_pb_tpl_folder)),
		$(call mb_printf_info, Project templates already downloaded$(mb_comma) skipping download.) \
	,
		$(call mb_printf_info, Downloading project templates)
		$(call mb_downloader, $(mb_pb_tpl_url), $(mb_pb_tpl_download_to))
		$(call mb_unzip, $(mb_pb_tpl_download_to), $(mb_pb_tpl_unzip_to))
		$(if $(wildcard $(mb_pb_tpl_folder)),
			$(call mb_printf_info, Project templates downloaded successfully)
		,
			$(call mb_printf_error, Project templates download failed)
		)
	)
endef

define mb_pb_create_project
$(strip
$(eval $0_project_type := $(strip $1))
$(eval $0_project_name := $(strip $(if $2, $2, generated_project)))
$(call mb_printf_info, Starting project creation)
$(call mb_pb_fetch_project_templates)
$(eval $0_pb_script_folder := $(mb_pb_folder)/$(subst _,/,$($0_project_type)))
$(eval $0_pb_script := $($0_pb_script_folder)/build.mk)

$(eval include $($0_pb_script))

$(call mb_pb_build,$($0_project_name))

)
endef


#mb_pb_php_symfony_replace ?= \
#  PROJECT_NAME $(mb_pb_project_name) \
#  PHP_IDE_CONFIG_SERVER_NAME $(mb_pb_project_name) \
#  POSTGRES_USER sy_user \
#  POSTGRES_PASSWORD sy_password \
#  POSTGRES_DB $(mb_pb_project_name)

# Symfony project creation command
# $1 = project template folder
# $2 = project name (optional, defaults to 'generated_project')
#define mb_pb_create_project_php_symfony
#
#$(eval $0_project_tpl_folder := $(strip $1))
#$(eval $0_project_name := $(strip $(if $2, $2, generated_project)))
#$(eval $0_project_path := /app/$($0_project_name))
#
#$(mb_modules_path)/project-builder/php/symfony.sh "$($0_project_tpl_folder)" "$(mb_project_path)" $($0_project_name) "$(mb_php_symfony_composer_packages)" "$(mb_php_symfony_composer_dev_packages)"
#endef




endif # __MB_MODULES_PROJECT_BUILDER_FUNCTIONS__

ifndef __MB_MODULES_PROJECT_BUILDER_TARGETS__
__MB_MODULES_PROJECT_BUILDER_TARGETS__ := 1

mb/project-builder: ## Project Builder module for MakeBind
	$(call mb_pb_create_project,php_symfony,blabla)

#$(eval $@_download_to := $(mb_makebind_tmp_path)/project_templates.zip)
#$(if $(wildcard $(mb_makebind_tmp_path)/project_templates-main),\
#	$(info Project templates already downloaded, skipping download.) \
#,\
#	$(info Downloading project templates...) \
#	$(call mb_downloader, $(pb_templates_url), $($@_download_to)) \
#	$(call mb_unzip, $($@_download_to), $(mb_makebind_tmp_path)) \
#)
#$(call mb_pb_create_project_php_symfony,$(mb_makebind_tmp_path)/project_templates-main,blabla)


endif # __MB_MODULES_PROJECT_BUILDER_TARGETS__
endif # __MB_MODULES_PROJECT_BUILDER_FUNCTIONS__