#####################################################################################
# Project: MakeBind
# File: modules/project-builder/project_builder.mk
# Description: Project Builder module for MakeBind
# Author: AntonioCS
# License: MIT License
#####################################################################################
ifndef __MB_MODULES_PROJECT_BUILDER__
__MB_MODULES_PROJECT_BUILDER__ := 1

ifndef __MB_MODULES_PROJECT_BUILDER_FUNCTIONS__
__MB_MODULES_PROJECT_BUILDER_FUNCTIONS__ := 1

mb_debug_pb ?= $(mb_debug)
mb_pb_folder ?= $(mb_modules_path)/project_builder
## NOTE: The contents seems to be inside a folder (generated by github)
## so the output folder is project_templates-main
mb_pb_tpl_url ?= https://github.com/AntonioCS/project_templates/archive/refs/heads/main.zip
mb_pb_tpl_download_to ?= $(mb_makebind_tmp_path)/project_templates.zip
mb_pb_tpl_unzip_to ?= $(mb_makebind_tmp_path)
mb_pb_tpl_folder ?= $(mb_makebind_tmp_path)/project_templates-main

mb_pb_project_builders ?= php_symfony php_laravel


define mb_pb_fetch_project_templates
$(if $(wildcard $(mb_pb_tpl_folder)),
		$(call mb_printf_info, Project templates already downloaded$(mb_comma) skipping download.) \
	,
		$(call mb_printf_info, Downloading project templates)
		$(call mb_downloader, $(mb_pb_tpl_url), $(mb_pb_tpl_download_to))
		$(call mb_unzip, $(mb_pb_tpl_download_to), $(mb_pb_tpl_unzip_to))
		$(if $(wildcard $(mb_pb_tpl_folder)),
			$(call mb_printf_info, Project templates downloaded successfully)
		,
			$(call mb_printf_error, Project templates download failed)
		)
	)
endef

define mb_pb_create_project
$(strip
$(eval $0_project_type := $(strip $1))
$(eval $0_project_name := $(strip $(if $2, $2, generated_project)))
$(call mb_printf_info, Starting project creation)
$(call mb_pb_fetch_project_templates)
$(eval $0_pb_script_folder := $(mb_pb_folder)/$(subst _,/,$($0_project_type)))
$(eval $0_pb_script := $($0_pb_script_folder)/build.mk)

$(info $($0_pb_script))
$(eval include $($0_pb_script))

$(call mb_pb_build,$($0_project_name))

)
endef


endif # __MB_MODULES_PROJECT_BUILDER_FUNCTIONS__

ifndef __MB_MODULES_PROJECT_BUILDER_TARGETS__
__MB_MODULES_PROJECT_BUILDER_TARGETS__ := 1


## TODO: Allow passing the project type
mb/project-builder/%: ## Project Builder module for MakeBind, pass <project_name> as argument
	$(eval $@_proj_name = $(strip $*))
	$(call mb_pb_create_project,php_symfony,$($@_proj_name))


endif # __MB_MODULES_PROJECT_BUILDER_TARGETS__
endif # __MB_MODULES_PROJECT_BUILDER_FUNCTIONS__