### Auto-generated by MakeBind
### Purpose: project overrides for module $(tpl_mod_name) defaults
### Usage: uncomment a line to override; lines use ':=' to force a value
### Generated: $(tpl_mod_gen_ts)
### Useful variables:
### - mb_makebind_path: Path to the MakeBind project
### - mb_modules_path: Path to MakeBind modules folder (not needed in mb_project_modules, if the module doesn't have a path this variable is used)
### - mb_project_makefile: Path to the Makefile of the project
### - mb_project_bindhub_path: Path to the bind.hub folder of the project
### - mb_project_bindhub_modules_path: Path to the modules folder in the bind-hub folder of the project
### - mb_project_path: Path of your project
