name: Run Tests on Pull Requests to Main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Tests
        working-directory: ./tests
        run: make
